In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

**https://numpy.org/**

**Array is a data structure in numpy**

In [4]:
sales = [3454,2344,2332,1232]
type(sales)

list

In [5]:
sales_array = np.array(sales)

In [7]:
type(sales_array)

numpy.ndarray

In [10]:
sales[0]=1111

In [11]:
sales_array[0]=2222

In [12]:
sales

[1111, 2344, 2332, 1232]

In [13]:
sales_array

array([2222, 2344, 2332, 1232])

**Similaries between Lists and Array**

1) Both can be used to store the data

2) The order will be preserved in both, indexing and slicing concepts will remain the same

3) Both are mutable in nature, we can change the values

**Differences between Lists and Arrays**

1) List is by default comes in with Python, however we need numpy package to get arrays

2) List can contain heterogenous data however, arrays can have homogeneous data

3) On the list we cannot perform vector operationsm we can do that in the arrays

4) Arrays consumes less memory than lists

5) Arrays are superfast when we compare it with lists

6) Arrays are more convinient for doing complex mathematical calculations

In [28]:
list1 = [True]

In [29]:
array1 = np.array(list1)

In [30]:
type(array1[0])

numpy.bool_

In [31]:
array1

array([ True])

In [32]:
sales

[1111, 2344, 2332, 1232]

In [34]:
profit = [ 122,332,323,121]

In [35]:
profit/sales

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [36]:
for i in range(len(sales)):
    print(profit[i]/sales[i])

0.10981098109810981
0.1416382252559727
0.13850771869639794
0.09821428571428571


In [37]:
profit_array = np.array(profit)

In [39]:
profit_array/sales_array

array([0.05490549, 0.14163823, 0.13850772, 0.09821429])

In [41]:
sales*3

[1111, 2344, 2332, 1232, 1111, 2344, 2332, 1232, 1111, 2344, 2332, 1232]

In [42]:
sales_array*3

array([6666, 7032, 6996, 3696])

In [47]:
sales_array.shape

(4,)

In [45]:
sales_array.size

4

In [48]:
sales_array.ndim

1

In [49]:
sales_array.mean()

2032.5

In [50]:
sales_us = [3222,4433,2312,1222]
sales_eu = [4333,2233,2334,3333]
sales_in = [1233,1456,4444,2344]

In [51]:
profit_us = [322,433,212,122]
profit_eu = [433,233,234,333]
profit_in = [233,146,444,234]

In [53]:
sales_matrix = np.array([sales_us,sales_eu,sales_in])

In [54]:
sales_matrix.shape

(3, 4)

In [55]:
sales_matrix.ndim

2

In [56]:
profit_matrix = np.array([profit_us,profit_eu,profit_in])

In [58]:
profit_matrix.shape

(3, 4)

In [61]:
np.round(profit_matrix/sales_matrix,3)

array([[0.1  , 0.098, 0.092, 0.1  ],
       [0.1  , 0.104, 0.1  , 0.1  ],
       [0.189, 0.1  , 0.1  , 0.1  ]])

In [62]:
sales_matrix

array([[3222, 4433, 2312, 1222],
       [4333, 2233, 2334, 3333],
       [1233, 1456, 4444, 2344]])

In [63]:
sales_matrix[2,2]

4444

In [66]:
sales_matrix[1:,1:3]

array([[2233, 2334],
       [1456, 4444]])

In [67]:
sales_matrix[0:2,2:4]

array([[2312, 1222],
       [2334, 3333]])

In [68]:
sales_matrix[0:2,2:]

array([[2312, 1222],
       [2334, 3333]])

In [71]:
sales_matrix

array([[3222, 4433, 2312, 1222],
       [4333, 2233, 2334, 3333],
       [1233, 1456, 4444, 2344]])

In [70]:
sales_matrix.mean()

2741.5833333333335

In [73]:
np.mean(sales_matrix,axis=1)

array([2797.25, 3058.25, 2369.25])

In [74]:
np.mean(sales_matrix,axis=0)

array([2929.33333333, 2707.33333333, 3030.        , 2299.66666667])

In [79]:
np.var(sales_matrix,axis=0)

array([1644493.55555556, 1589584.22222222,  999778.66666667,
        743702.88888889])

In [81]:
sales_matrix[np.where(sales_matrix>4000)]

array([4433, 4333, 4444])

In [82]:
sales_matrix

array([[3222, 4433, 2312, 1222],
       [4333, 2233, 2334, 3333],
       [1233, 1456, 4444, 2344]])

In [83]:
np.where(sales_matrix>4000)

(array([0, 1, 2], dtype=int64), array([1, 0, 2], dtype=int64))

**Pandas**

In [84]:
import pandas as pd

**https://pandas.pydata.org/**

In [85]:
pd.__version__

'1.5.3'

In [87]:
student_details = {'sid':[1,2,3,4,5], 'stuname':['A','B','C','D','E'], 'sturegion':['N','W','S','W','E']}

In [88]:
student_details

{'sid': [1, 2, 3, 4, 5],
 'stuname': ['A', 'B', 'C', 'D', 'E'],
 'sturegion': ['N', 'W', 'S', 'W', 'E']}

In [102]:
student_marks = {'s_id':[1,2,3,4,6], 'stusub':['Py','R','Tableau','SQL','Py'], 'stumarks':[10,12,13,14,21]}

In [90]:
student_marks

{'sid': [1, 2, 3, 4, 6],
 'stusub': ['Py', 'R', 'Tableau', 'SQL', 'Py'],
 'stumarks': [10, 12, 13, 14, 21]}

In [91]:
df1 = pd.DataFrame(student_details)

In [103]:
df2 = pd.DataFrame(student_marks)

In [93]:
type(df1)

pandas.core.frame.DataFrame

In [104]:
df1

sid stuname sturegion
0    1       A         N
1    2       B         W
2    3       C         S
3    4       D         W
4    5       E         E

In [105]:
df2

s_id   stusub  stumarks
0     1       Py        10
1     2        R        12
2     3  Tableau        13
3     4      SQL        14
4     6       Py        21

In [101]:
pd.merge(df1,df2,on='sid',how='outer')

sid stuname sturegion   stusub  stumarks
0    1       A         N       Py      10.0
1    2       B         W        R      12.0
2    3       C         S  Tableau      13.0
3    4       D         W      SQL      14.0
4    5       E         E      NaN       NaN
5    6     NaN       NaN       Py      21.0

In [108]:
pd.merge(df1,df2,left_on='sid', right_on='s_id')

sid stuname sturegion  s_id   stusub  stumarks
0    1       A         N     1       Py        10
1    2       B         W     2        R        12
2    3       C         S     3  Tableau        13
3    4       D         W     4      SQL        14

In [109]:
student_details = {'sid':[1,2,3,4,5], 'stuname':['A','B','C','D','E'], 'sturegion':['N','W','S','W','E']}

In [110]:
student_marks = {'s_id':[1,2,3,4,6], 'stuname':['A','B','C','D','F'],'stusub':['Py','R','Tableau','SQL','Py'], 'stumarks':[10,12,13,14,21]}

In [111]:
df1 = pd.DataFrame(student_details)

In [112]:
df2 = pd.DataFrame(student_marks)

In [113]:
df1

sid stuname sturegion
0    1       A         N
1    2       B         W
2    3       C         S
3    4       D         W
4    5       E         E

In [114]:
df2

s_id stuname   stusub  stumarks
0     1       A       Py        10
1     2       B        R        12
2     3       C  Tableau        13
3     4       D      SQL        14
4     6       F       Py        21

In [118]:
pd.merge(df1,df2,left_on=('sid','stuname'), right_on=('s_id','stuname'))

sid stuname sturegion  s_id   stusub  stumarks
0    1       A         N     1       Py        10
1    2       B         W     2        R        12
2    3       C         S     3  Tableau        13
3    4       D         W     4      SQL        14

In [119]:
customer_table = {'cust_id':[1,2,3,4,5], 'cust_name':['A','B','C','D','E'], 'cust_region':['N','S','S','W','E']}

loan_table = {'cust_id':[1,2,3,4,5],'loan_id':[10,20,30,40,50],'loan_amt':[123,321,132,134,222]}

agent_table = {'agent_id':[101,102,101,102,102], 'agent_name':['James','John','James','John','John'], 'loan_id':[10,20,30,40,50]}


In [121]:
df1 = pd.DataFrame(customer_table)

In [122]:
df2 = pd.DataFrame(loan_table)

In [123]:
df3 = pd.DataFrame(agent_table)

In [124]:
df1

cust_id cust_name cust_region
0        1         A           N
1        2         B           S
2        3         C           S
3        4         D           W
4        5         E           E

In [125]:
df2

cust_id  loan_id  loan_amt
0        1       10       123
1        2       20       321
2        3       30       132
3        4       40       134
4        5       50       222

In [126]:
df3

agent_id agent_name  loan_id
0       101      James       10
1       102       John       20
2       101      James       30
3       102       John       40
4       102       John       50

In [128]:
pd.merge(pd.merge(df1,df2),df3)

cust_id cust_name cust_region  loan_id  loan_amt  agent_id agent_name
0        1         A           N       10       123       101      James
1        2         B           S       20       321       102       John
2        3         C           S       30       132       101      James
3        4         D           W       40       134       102       John
4        5         E           E       50       222       102       John

In [130]:
customer_table_US = {'cust_id':[1,2,3,4,5], 'cust_name':['A','B','C','D','E'], 'cust_region':['N_US','S_US','S_US','W_US','E_US']}

In [129]:
customer_table_IND = {'cust_id':[6,7,8,9,5], 'cust_name':['P','Q','R','S','E'], 'cust_region':['N_IND','S_IND','S_IND','W_IND','E_US']}

In [133]:
df1 = pd.DataFrame(customer_table_IND)

In [134]:
df2 = pd.DataFrame(customer_table_US)

In [135]:
df1

cust_id cust_name cust_region
0        6         P       N_IND
1        7         Q       S_IND
2        8         R       S_IND
3        9         S       W_IND
4        5         E        E_US

In [136]:
df2

cust_id cust_name cust_region
0        1         A        N_US
1        2         B        S_US
2        3         C        S_US
3        4         D        W_US
4        5         E        E_US

In [139]:
pd.concat([df1,df2],axis=1)

cust_id cust_name cust_region  cust_id cust_name cust_region
0        6         P       N_IND        1         A        N_US
1        7         Q       S_IND        2         B        S_US
2        8         R       S_IND        3         C        S_US
3        9         S       W_IND        4         D        W_US
4        5         E        E_US        5         E        E_US

In [156]:
output  = pd.concat([df1,df2],axis=0).reset_index().drop_duplicates().drop('index',axis=1)

In [157]:
output

cust_id cust_name cust_region
0        6         P       N_IND
1        7         Q       S_IND
2        8         R       S_IND
3        9         S       W_IND
4        5         E        E_US
5        1         A        N_US
6        2         B        S_US
7        3         C        S_US
8        4         D        W_US

In [155]:
pd.concat([df1,df2],axis=0).reset_index().drop_duplicates()

index  cust_id cust_name cust_region
0      0        6         P       N_IND
1      1        7         Q       S_IND
2      2        8         R       S_IND
3      3        9         S       W_IND
4      4        5         E        E_US
5      0        1         A        N_US
6      1        2         B        S_US
7      2        3         C        S_US
8      3        4         D        W_US

In [154]:
output

In [143]:
output = pd.concat([df1,df2],axis=0).reset_index()

In [147]:
output.drop('index',axis=1,inplace=True)

In [148]:
output

cust_id cust_name cust_region
0        6         P       N_IND
1        7         Q       S_IND
2        8         R       S_IND
3        9         S       W_IND
4        5         E        E_US
5        1         A        N_US
6        2         B        S_US
7        3         C        S_US
8        4         D        W_US
9        5         E        E_US

**Scenario 1**

In [161]:
output = pd.concat([df1,df2]).reset_index().drop_duplicates()

In [165]:
output = output.drop('index',axis=1)

In [166]:
output

cust_id cust_name cust_region
0        6         P       N_IND
1        7         Q       S_IND
2        8         R       S_IND
3        9         S       W_IND
4        5         E        E_US
5        1         A        N_US
6        2         B        S_US
7        3         C        S_US
8        4         D        W_US

**Scenario 2**

In [167]:
output = pd.concat([df1,df2]).reset_index().drop_duplicates()

In [171]:
output.drop('index',axis=1,inplace=True)

In [172]:
output

cust_id cust_name cust_region
0        6         P       N_IND
1        7         Q       S_IND
2        8         R       S_IND
3        9         S       W_IND
4        5         E        E_US
5        1         A        N_US
6        2         B        S_US
7        3         C        S_US
8        4         D        W_US

In [175]:
output.iloc[:,0:2]

cust_id cust_name
0        6         P
1        7         Q
2        8         R
3        9         S
4        5         E
5        1         A
6        2         B
7        3         C
8        4         D

In [177]:
output.iloc[0:5,:]

cust_id cust_name cust_region
0        6         P       N_IND
1        7         Q       S_IND
2        8         R       S_IND
3        9         S       W_IND
4        5         E        E_US

In [180]:
output.iloc[0:4,1:3]

cust_name cust_region
0         P       N_IND
1         Q       S_IND
2         R       S_IND
3         S       W_IND

In [187]:
output.iloc[[0,5,8], [0,2]].values

array([[6, 'N_IND'],
       [1, 'N_US'],
       [4, 'W_US']], dtype=object)

In [192]:
pd.DataFrame(sales_matrix,columns=['Q1','Q2','Q3','Q4'])       

Q1    Q2    Q3    Q4
0  3222  4433  2312  1222
1  4333  2233  2334  3333
2  1233  1456  4444  2344

In [202]:
output.iloc[:,-1:-3:-1]

cust_region cust_name
0       N_IND         P
1       S_IND         Q
2       S_IND         R
3       W_IND         S
4        E_US         E
5        N_US         A
6        S_US         B
7        S_US         C
8        W_US         D